
>> eval("function fib (n) {if (n<=1) {return n;} return fib(n-1) + fib(n-2);}") ;

println("fib until 10");
var s = "";
for (var i = 1; i <= 10; i+=1) s+=fib(i)+" ";
println(s);

println("fib until 10 with eval expr:");
>> eval("s = ''; for (var i = 1; i <= 10; i+=1) { s+=fib(i) + ' '; } println(s);");

var fib_code = "s = ''; for (var i = 1; i <= 10; i+=1) s+=fib(i) + ' '; println(s);";
println("fib until 10 with eval assignment, double print:");
var res = eval(fib_code+">> s;");
println(res);
